# Generated by Django 4.0.4 on 2022-07-20 13:53

import cinema.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(blank=True, default=1, upload_to=cinema.models.movie_image_file_path),
            preserve_default=False,
        ),
    ]
