# Generated by Django 4.1 on 2023-12-06 15:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cinema", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="genre",
            options={"ordering": ["name"]},
        ),
    ]
