# Generated by Django 4.1 on 2024-05-12 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "cinema",
            "0004_alter_movie_actors_alter_movie_description_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="description",
            field=models.TextField(),
        ),
    ]
