# Generated by Django 4.1 on 2024-08-02 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0004_alter_movie_actors_alter_movie_genres"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="actors",
            field=models.ManyToManyField(blank=True, to="cinema.actor"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="genres",
            field=models.ManyToManyField(blank=True, to="cinema.genre"),
        ),
    ]
